### ISSUE TITLE
404 Error on Page Refresh in Vercel Deployment

### ISSUE THREAD

**Issue by chirag-63** [sidonweb/medium-clone#1]
**ISSUE** : Whenever I try to refresh on any of the pages (except base url), it shows 404 Error on that page.

![Screenshot 2024-07-05 145018](https://github.com/sidonweb/medium-clone/assets/146445120/e9e54a9e-6d8f-499a-b604-73c09acc6aa9)
.
I believe this is due to some vercel deployment issues.
you should  add a vercel.json file to frontend directory.

checkout this for more :
[How to fix 404 Error on refreshing page](https://stackoverflow.com/questions/65475998/how-to-fix-an-error-code-not-found-in-vercel)

_Note:_
I can fix it, if you assign this issue to me.

**Comment by sidonweb** [comment]
Thanks for the heads up! I'm looking forward to getting it fixed :)

**Comment by chirag-63** [comment]
I am getting [this](https://github.com/meilisearch/demos/issues/43) error while generating a pull request. my pull request fails automatically. 

can u disable git fork protection in `/settings/security` so that pull request can be merged.
